daemon:
    name: Astron Cluster

general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    connect: 127.0.0.1:7199

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: PiratesSettingsMgr
      id: 4704
      anonymous: true

    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: DistributedTravelAgent
      id: 4679
      anonymous: false

    - class: DistributedInventoryManager
      id: 4677
      anonymous: false

    - class: HolidayManager
      id: 4705
      anonymous: false

    - class: CodeRedemption
      id: 4703
      anonymous: false

roles:
    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999